spring:
  application:
    name: gateway-zuul # 指定应用名称

  cloud:
    inetutils:
      preferred-networks:
      - 10.0   # 设置注册到Eureka中心的优选服务地址

server:
  port: 8050

eureka:
  instance:
      prefer-ip-address: true  #优选通过IP地址找到对应的服务名称

  client:
    #配置eureka注册中心地址
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#      上线测试需要使用以下配置
      defaultZone: http://eureka-server:8761/eureka/

#设置Hystrix熔断器判定超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
zuul:
  ignoredServices: '*'
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
    order-service:
       path: /order-service/**
       serviceId: order-service
